
/* Declarations from the module resource file */
#include "IrisModuleManagedPrototype.uf.h"



int     UserFunction (
	 cxGeneric *	  geomIn, 
	 cxLattice *	  latOut, 
	 cxLattice *	  latIn )
{

}

#include <cx/UserFuncs.h>

#ifdef __cplusplus
	extern "C" {
#endif
/* Hook function for Explorer module actions. */
void Init(void)
{

}
/* Hook function for Explorer module actions. */
void Remove(void)
{

}
/* Hook function for Explorer module actions. */
void Create(void)
{

}
/* Hook function for Explorer module actions. */
void ConnectIn(const char *portName, int linkTag )
{

}
/* Hook function for Explorer module actions. */
void ConnectOut(const char *portName, int linkTag )
{

}
/* Hook function for Explorer module actions. */
void DisconnectIn(const char *portName, int linkTag )
{

}
/* Hook function for Explorer module actions. */
void DisconnectOut(const char *portName, int linkTag )
{

}

#ifdef __cplusplus
}
#endif

